### PR TITLE
Minor updates to distribution's moment estimation

### PR DESCRIPTION
**Pull request by chartgerink**
This PR implements improvements I observed in #240. 

I had to update the test for the Weibull kurtosis because it failed (based on prior version). I verified that the new calculation is correct - [see also this Weibull calculator](https://www.solvemymath.com/online_math_calculator/statistics/continuous_distributions/weibull/param_weibull.php).

### CODE REVIEW

**Comment by chartgerink** [comment]
Sorry for the force pushes, but it seemed like I had to escape issues that I hadn't created regarding linting (which caused issues in the tests). Hope this works now.

**Comment by joshwlambert** [comment]
Thanks for the updates and explanation in #240. Updates look good to me. @chartgerink are you happy for this PR to be merged without any further changes or are you planning on continuing to work on it?

**Comment by chartgerink** [comment]
@joshwlambert - thanks for checking in! I am happy for these to be handled as is. 

I am still planning on finding some time for the other in #240, which I'll open a separate PR for if needed 👍

**Comment by joshwlambert** [comment]
Closing and reopening PR to trigger GHA workflows after GHA commit.

**Review by joshwlambert — APPROVED** [review]

**Comment by joshwlambert** [comment]
@chartgerink thanks so much for this work! 🙌

**Pull request merged**
